### ISSUE TITLE
Installing and running web application

### ISSUE THREAD

**Issue by ericawho** [mehtab-alam/GeospaCy#1]
I'm unable to install and run this repository in Windows. Do you have a working example of a python workbook? Thank you

**Comment by mehtab-alam** [comment]
Currently, I tried it on the LINUX/MAC machines. Could you please share me the error exactly (where exactly you are facing the issue)? Thank you!

**Comment by ericawho** [comment]
Please see attached immage, thank you! 
![image](https://github.com/mehtab-alam/GeospaCy/assets/165982135/0180e156-eedc-44e3-9a44-f84a48909cc0)

**Comment by mehtab-alam** [comment]
The problem seems to me is that : On your command line you are not in the right directory. So the steps are:

Step 1: cd [DIRECTORY of [1_🏠_Parser.py](https://github.com/mehtab-alam/GeospaCy/blob/master/1_%F0%9F%8F%A0_Parser.py)]

Step 2: streamlit run 1_🏠_Parser.py

**Comment by ericawho** [comment]
thank you, i realized i misread my file pathing. i was able to progress to opening the app, but now i encounter this error:"**ModuleNotFoundError: No module named 'geospacy**'" even though i have checked that i installed all the necessary packages. thank you; i'm new to python and geoparsing!

**Comment by paddysmith99** [comment]
I am having the same issue, any guidance would be greatly appreciated!

**Comment by mehtab-alam** [comment]
> I am having the same issue, any guidance would be greatly appreciated!

Could you please install all the necessary libraries required for running geoSpaCy... e.g. 
```sh
pip install -r /path/to/requirements.txt 
```

**Comment by paddysmith99** [comment]
is this via command prompt? I apologise but I am not well versed in Python. Would it be possible to share script to run the web application?

**Comment by mehtab-alam** [comment]
> is this via command prompt? I apologise but I am not well versed in Python. Would it be possible to share script to run the web application?

Yes, If you follow the [README](https://github.com/mehtab-alam/GeospaCy/blob/master/README.md) through the command prompt. You will be able to run the web application

**Comment by paddysmith99** [comment]
Okay thank you. I have followed README, but am receiving this error: ModuleNotFoundError: No module named 'geospacy'

**Comment by mehtab-alam** [comment]
> Okay thank you. I have followed README, but am receiving this error: ModuleNotFoundError: No module named 'geospacy'

Could you please attached the screenshots and steps to reproduce this error ?

**Comment by paddysmith99** [comment]
The above error was my mistake. I've solved this now, but now getting this error (see attached). I presume its something to do with requirements.txt. When I try and install that, I get another error
![Screenshot 2024-05-15 115207](https://github.com/mehtab-alam/GeospaCy/assets/89030472/d043f249-bb67-44f5-a7b0-6ea554750728)
![Screenshot 2024-05-15 115128](https://github.com/mehtab-alam/GeospaCy/assets/89030472/abaf3f6c-9ce7-426b-82bb-36de7f015c7c)

**Comment by mehtab-alam** [comment]
> The above error was my mistake. I've solved this now, but now getting this error (see attached). I presume its something to do with requirements.txt. When I try and install that, I get another error ![Screenshot 2024-05-15 115207](https://private-user-images.githubusercontent.com/89030472/330773146-d043f249-bb67-44f5-a7b0-6ea554750728.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzA2NTcsIm5iZiI6MTcxNTc3MDM1NywicGF0aCI6Ii84OTAzMDQ3Mi8zMzA3NzMxNDYtZDA0M2YyNDktYmI2Ny00NGY1LWE3YjAtNmVhNTU0NzUwNzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzk4ZTRlNWY5ODFiMDk1MTA0YTNjOWY2NjhkMTcwYjE0YWRjZmI1NDBkYWNiY2VmYTBjZjYzNzQ4ZTc4N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzEt1bLUmvkl7LzfSTMKmyf-2Ym2Wwl5yAaj4-tOOGg) ![Screenshot 2024-05-15 115128](https://private-user-images.githubusercontent.com/89030472/330773148-abaf3f6c-9ce7-426b-82bb-36de7f015c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzA2NTcsIm5iZiI6MTcxNTc3MDM1NywicGF0aCI6Ii84OTAzMDQ3Mi8zMzA3NzMxNDgtYWJhZjNmNmMtOWNlNy00MjZiLTgyYmItMzZkZTdmMDE1YzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Zjc1YjkxYjFlYTFhODY4ZjI3MmE1OTc0ODIyOGIxZGJjMzc0MjVhMjA3NGY0YTM1Nzk4NDVhNjAxMTczOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAdU56YlmgjUoABZPi8ayfTbBojI-A9fZrqRgOxwpA0)

By default, the spaCy language model "en_core_web_sm" is installed with the spaCy library. If you want to install other language models, for instance "en_core_web_md", you have to use the following command:

```sh
python -m spacy download en_core_web_md
```

**Comment by paddysmith99** [comment]
that solved it. Now getting this error

![image](https://github.com/mehtab-alam/GeospaCy/assets/89030472/8464567e-2fbe-4687-bab2-825a3ceac97a)

**Comment by mehtab-alam** [comment]
> that solved it. Now getting this error
> 
> ![image](https://private-user-images.githubusercontent.com/89030472/330778288-8464567e-2fbe-4687-bab2-825a3ceac97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzE1MzQsIm5iZiI6MTcxNTc3MTIzNCwicGF0aCI6Ii84OTAzMDQ3Mi8zMzA3NzgyODgtODQ2NDU2N2UtMmZiZS00Njg3LWJhYjItODI1YTNjZWFjOTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExMDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YWFiYTE0OGEwNjNkOTNkNTlhYzY0M2M5MTM2MDgyNTU0MDA3NTUyNDhlNzg4ZTY0NGQ4ZDg5NjkyOGM2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vu2U5Xype_Ps4Vid9i3qbpo-yZN37lLKJU1vEE2sZOA)

<img width="919" alt="image" src="https://github.com/mehtab-alam/GeospaCy/assets/8651552/573b4a76-9dd6-4f9c-9538-dd3015023ad9">


You didn't have the **tetis-1.png** in your root directory of the code (see the above screenshot).

**Comment by paddysmith99** [comment]
It is definitely saved in the same directory as the parser - I have saved all the folder 'GeospaCy-1.0.0' with all files inside of it
 
![image](https://github.com/mehtab-alam/GeospaCy/assets/89030472/320c70a2-7d87-45b8-b986-822e28b845ca)

**Comment by mehtab-alam** [comment]
> It is definitely saved in the same directory as the parser - I have saved all the folder 'GeospaCy-1.0.0' with all files inside of it
> 
> ![image](https://private-user-images.githubusercontent.com/89030472/330784498-320c70a2-7d87-45b8-b986-822e28b845ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzQ4NzEsIm5iZiI6MTcxNTc3NDU3MSwicGF0aCI6Ii84OTAzMDQ3Mi8zMzA3ODQ0OTgtMzIwYzcwYTItN2Q4Ny00NWI4LWI5ODYtODIyZTI4Yjg0NWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NWFkYzdkZTY1MjkxZmQzNDFjN2Y3NTFkMTdlOTg4NWMxZDBmNGVjYTA5ODRjY2JiYTgxNDRiNjI5MzYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._QcobaZ5Y01zIy3WPuBTsWbpGbxF8uF4dYx3j5WEeh8)

The error you shown previously is telling about the missing file **tetis-1.png**.

**Comment by paddysmith99** [comment]
Is it possible to provide a solution to this? As I have followed the steps but still receiving an error code. Thanks

**Comment by mehtab-alam** [comment]
> Is it possible to provide a solution to this? As I have followed the steps but still receiving an error code. Thanks

The second solution is to comment or remove the following code from [1_🏠_Parser.py](https://github.com/mehtab-alam/GeospaCy/blob/master/1_%F0%9F%8F%A0_Parser.py) :

```python
   st.markdown(
        f"""
        <div class="container">
            <img class="logo-img" src="data:image/png;base64,{base64.b64encode(open(LOGO_IMAGE, "rb").read()).decode()}">
            <p class="logo-text">GeOspaCy</p>
        </div>
        """,
        unsafe_allow_html=True
    )
```

**Comment by paddysmith99** [comment]
That seemed to work. I have this error now. I have ran this code in command prompt but still gets this error. Thanks for all your help so far!!

![image](https://github.com/mehtab-alam/GeospaCy/assets/89030472/797b5683-5f39-4a5c-af5a-cb0c1c05e0f7)

**Comment by mehtab-alam** [comment]
> That seemed to work. I have this error now. I have ran this code in command prompt but still gets this error. Thanks for all your help so far!!
> 
> ![image](https://private-user-images.githubusercontent.com/89030472/330826415-797b5683-5f39-4a5c-af5a-cb0c1c05e0f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODI4OTQsIm5iZiI6MTcxNTc4MjU5NCwicGF0aCI6Ii84OTAzMDQ3Mi8zMzA4MjY0MTUtNzk3YjU2ODMtNWYzOS00YTVjLWFmNWEtY2IwYzFjMDVlMGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE0MTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZGE5YWZiNjQ3NzYzNTdjZjE2ZjYxNDViMmZkNmNlZmNkYzQ1YjMyY2U2MDY5YTIwZTU2YzUzYjFiNTEwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RExKA4-LlZXip1V3qx_K8MFkpPfQT8y7T0RBuwaVGSA)

Yes, there are possibility of the bugs in the code. So you have to add the free text as syntactically correct with proper punctuations e.g. commas, full stop etc.

Here is the example of text:

````{verbatim}
African Swine Fever (ASF) has been detected in a sample from 7 wild boar
found just south-east of Fagersta. The Czech Republic has found a second case of the bird flu virus, at a commercial poultry farm, an Agriculture Ministry spokesman said
on Sunday. The spokesman said more details of the case, in a region east of Prague. France has detected a highly pathogenic strain of bird flu in a pet shop near Paris, days after an identical outbreak in one of Corsica’s main cities.
````

See the example output :

<img width="1265" alt="image" src="https://github.com/mehtab-alam/GeospaCy/assets/8651552/ca2510ca-a992-4740-81b6-12ff6b7c5caf">
